--- #YAML:1.0
name: 				Net-Rapidshare
abstract: 			Perl interface to Rapidshare API
version: 			0.05
author:
	- Mithun Ayachit <mithun@cpan.org>
license: 			perl
distribution_type: 	module
requires:
	Test::More: 	0
	LWP::UserAgent: 0
	HTML::Entities: 0
no_index:
    directory:
        - t
		- examples
resources:
	license: 		http://dev.perl.org/licenses/
	bugtracker: 	http://github.com/mithun/perl-net-rapidshare/issues
	repository: 	http://github.com/mithun/perl-net-rapidshare
meta-spec:
	version: 		1.4
	url: 			http://module-build.sourceforge.net/META-spec-v1.3.html