---
name: Net-Rapidshare
version: 0.06
author:
  - 'Mithun Ayachit <mithun at cpan dot org>'
abstract: Perl interface to the Rapidshare API
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Entities: 0
  LWP::UserAgent: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Net::Rapidshare:
    file: lib/Net/Rapidshare.pm
    version: 0.06
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
